replicaCount: 1

namespace: baruchi

image:
  repository: baruchi-pipelines
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: baruchi-service
  appSelector: baruchi-app
  type: LoadBalancer
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: baruchi.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}